[metadata]
name = myframework
version = 0.1
author = Tu Nombre
description = Micro framework web en Python
license = MIT
long_description_content_type = text/markdown

[options]
packages = find:
include_package_data = true
python_requires = >=3.7

[options.package_data]
myframework = templates/*.html

[options.entry_points]
console_scripts =
    myframework-scaffold = myframework.scripts.scaffold:main